#####网页站源

####
###type
web
###分类
网页站源
###标题
直播盒子
###图片
https://tse1-mm.cn.bing.net/th/id/OIP-C.AJZyG2eEuj5DMtYgCkeoPAHaMW?w=113&h=180&c=7&r=0&o=5&pid=1.7
###BaseURL
"http://api.vipmisss.com:81";
###首页地址
"http://api.hclyz.com:81/mf/json.txt";
###分类地址
getVar("baseURL")+"/分类/json.txt翻页";
###搜索地址
"http://ip111.cn/?wd=关键字翻页";
###rule
##首页规则
var 列表=e2Arr(getVar("源码"),".json(pingtai)");var 标题规则=".json(title)";var 地址规则=".c(http://api.hclyz.com:81/mf/).json(address)";var 图片规则=".json(xinimg)";var 简介规则=".json(Number).ct(位主播)";var 图片底部规则="@js='';";var 左上规则="@js='';";var 右上规则="@js='';";var NEXTPAGE="";var PREPAGE="";
##筛选数据
var a="分类+xcdsw";var b="翻页+全部=";a+"\n"+b;
##分类规则
var 列表=e2Arr(getVar("源码"),".json(pingtai)");var 标题规则=".json(title)";var 地址规则=".c(/xcdsw/).json(address)";var 图片规则=".json(xinimg)";var 简介规则=".json(Number).ct(位主播)";var 图片底部规则="@js='';";var 左上规则="@js='';";var 右上规则="@js='';";var NEXTPAGE="";var PREPAGE="";
##选集规则
var 分类=e2Arr(getVar("源码"),".all()");var 简介=".var(标题)";var 线路="";var 列表规则=".json(zhubo)";var 标题规则=".var(标题)";var 选集规则=".json(title)";var 选集地址规则="@js=\"http://ip111.cn/?wd=\"+e2(列表[j],\".json(address)\").replace(/\\?/g,\"幻魔快修\");";
##搜索规则
var 源码=getHttp(JSON.stringify({url:"http://api.vipmisss.com:81/xcdsw/json.txt"}));var 列表=e2Arr(源码,".json(pingtai)").filter(item=>item.indexOf(getVar("关键字"))!=-1);if(!列表[0]){var 列表=["未匹配到任何平台"];var 标题规则=".t()";var 地址规则="@js=getVar(\"baseURL\");";var 图片规则=".get(img).a(data-original)";var 简介规则="@js='未匹配到任何平台';";var 图片底部规则="@js='';";var 左上规则="@js='';";var 右上规则="@js='';";var NEXTPAGE="";var PREPAGE="";}else{var 标题规则=".json(title)";var 地址规则=".c(/xcdsw/).json(address)";var 图片规则=".json(xinimg)";var 简介规则=".json(Number).ct(位主播)";var 图片底部规则="@js='';";var 左上规则="@js='';";var 右上规则="@js='';";var NEXTPAGE="";var PREPAGE="";}
##搜索翻页
var b="翻页+全部=";b;
##免嗅探规则
JSON.stringify([{name:"地址",url:getVar("地址").split("?wd=")[1].replace(/幻魔快修/g,"?")}]);
####
####
###type
iptv
###分类
iptv
###数据
视频
##
远程$https://gh.llkk.cc/https://raw.githubusercontent.com/CJ-Hot/feeds/main/live/18v.m3u
####
####
###type
iptv
###分类
iptv
###数据
直播
##
远程$https://gh.llkk.cc/https://raw.githubusercontent.com/CJ-Hot/feeds/main/live/18live.m3u
####

#####


#####cms
####
###type
cms
###分类
cms
###标题
155资源
###图片
https://www.seekhill.com/wp-content/uploads/2022/03/20220318123440.png
###BaseURL
"https://155api.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
cms
###标题
优异资源
###图片
https://www.seekhill.com/wp-content/uploads/2022/03/20220318123440.png
###BaseURL
"https://a.uezy.pw/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
cms
###标题
老色逼资源
###图片
https://www.seekhill.com/wp-content/uploads/2022/03/20220318123440.png
###BaseURL
"https://apilsbzy1.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
cms
###标题
橘猫资源(丝袜)
###图片
https://www.seekhill.com/wp-content/uploads/2022/03/20220318123440.png
###BaseURL
"https://to.to-long.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
cms
###标题
色猫资源
###图片
https://www.seekhill.com/wp-content/uploads/2022/03/20220318123440.png
###BaseURL
"https://caiji.semaozy.net/inc/apijson_vod.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
cms
###标题
滴滴资源
###图片
https://www.seekhill.com/wp-content/uploads/2022/03/20220318123440.png
###BaseURL
"https://api.ddapi.cc/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
cms
###标题
奶香香资源
###图片
https://www.seekhill.com/wp-content/uploads/2022/03/20220318123440.png
###BaseURL
"https://naixxzy.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
cms
###标题
美少女资源
###图片
https://www.seekhill.com/wp-content/uploads/2022/03/20220318123440.png
###BaseURL
"https://www.msnii.com/api/json.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
cms
###标题
淫水机资源
###图片
https://www.seekhill.com/wp-content/uploads/2022/03/20220318123440.png
###BaseURL
"https://www.xrbsp.com/api/json.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
cms
###标题
香奶儿资源
###图片
https://www.seekhill.com/wp-content/uploads/2022/03/20220318123440.png
###BaseURL
"https://www.gdlsp.com/api/json.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
cms
###标题
白嫖资源
###图片
https://www.seekhill.com/wp-content/uploads/2022/03/20220318123440.png
###BaseURL
"https://www.kxgav.com/api/json.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
cms
###标题
黄AV资源
###图片
https://www.seekhill.com/wp-content/uploads/2022/03/20220318123440.png
###BaseURL
"https://www.pgxdy.com/api/json.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
cms
###标题
大地资源
###图片
https://www.seekhill.com/wp-content/uploads/2022/03/20220318123440.png
###BaseURL
"https://dadiapi.com/api.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
cms
###标题
乐播资源
###图片
https://www.seekhill.com/wp-content/uploads/2022/03/20220318123440.png
###BaseURL
"https://lbapi9.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
cms
###标题
富二代资源
###图片
https://www.seekhill.com/wp-content/uploads/2022/03/20220318123440.png
###BaseURL
"http://f2dcj6.com/sapi";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
cms
###标题
putaozyw
###图片
https://www.seekhill.com/wp-content/uploads/2022/03/20220318123440.png
###BaseURL
"https://caiji.putaozyw.net/inc/apijson_vod.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
cms
###标题
auezy
###图片
https://www.seekhill.com/wp-content/uploads/2022/03/20220318123440.png
###BaseURL
"https://a.uezy.pw/api.php/provide/vod/at/json";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
cms
###标题
apilsbzy1
###图片
https://www.seekhill.com/wp-content/uploads/2022/03/20220318123440.png
###BaseURL
"https://apilsbzy1.com/api.php/provide/vod/at/json";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
cms
###标题
xrbsp
###图片
https://www.seekhill.com/wp-content/uploads/2022/03/20220318123440.png
###BaseURL
"https://www.xrbsp.com/api/json.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
cms
###标题
gdlsp
###图片
https://www.seekhill.com/wp-content/uploads/2022/03/20220318123440.png
###BaseURL
"https://www.gdlsp.com/api/json.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
cms
###标题
kxgav
###图片
https://www.seekhill.com/wp-content/uploads/2022/03/20220318123440.png
###BaseURL
"https://www.kxgav.com/api/json.php";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####

#####