#####iptv

####
###type
iptv
###分类
iptv
###数据
EPG每日更新
##
远程$https://epg.pw/test_channels.txt
####
####
###type
iptv
###分类
iptv
###数据
MV
##
远程$https://gh.llkk.cc/https://raw.githubusercontent.com/CJ-Hot/feeds/main/live/mv.m3u
####
####
###type
iptv
###分类
iptv
###数据
视频
##
远程$https://gh.llkk.cc/https://raw.githubusercontent.com/CJ-Hot/feeds/main/live/v.m3u
####
####
###type
iptv
###分类
iptv
###数据
直播
##
远程$https://gh.llkk.cc/https://raw.githubusercontent.com/CJ-Hot/feeds/main/live/live.m3u
####

#####


#####网页影视站源

####
###type
web
###分类
网页影视站源
###标题
555电影
###图片
https://vpic.cms.qq.com/nj_vpic/3272248629/1738571619832751129/5716822510667367545
###BaseURL
"https://www.fkowxun.shop/";
###首页地址
getVar("baseURL")+"/vodtype/124.html";
###分类地址
getVar("baseURL")+"/vodshow/分类-----翻页---.html";
###搜索地址
getVar("baseURL")+"/vodsearch/关键字----------翻页---.html";
###rule
##首页规则
var 列表=e2Arr(getVar("源码"),".get(div.module-items a.module-item)");if(!列表[0]){var 列表=["网页可能有搜索验证，去网页看看吧"];var 标题规则=".t()";var 地址规则="@js=getVar(\"当前请求地址\");";var 图片规则=".get(img).a(data-original)";var 简介规则="长按网页打开，验证后返回重新搜索即可";var 图片底部规则="@js='';";var 左上规则="@js='';";var 右上规则="@js='';";var NEXTPAGE="";var PREPAGE="";}else{var 标题规则=".get(a).a(title)";var 地址规则=".get(a).a(href)";var 图片规则=".get(img).a(data-original)";var 简介规则=".t()";var 图片底部规则="@js='';";var 左上规则="@js='';";var 右上规则="@js='';";var NEXTPAGE="";var PREPAGE="";}
##筛选数据
var a="分类+电影=1---+电视剧=2---+福利=124---+动漫=4---+Netflix电影=1---Netflix+Netflix剧=2---Netflix+剧情片=1---剧情+科幻片=1---科幻+动作片=1---动作+喜剧片=1---喜剧+爱情片=1---爱情+大陆剧=2-大陆--+香港剧=2-香港--+韩剧=2-韩国--+美剧=2-美国--+日剧=2-日本--";var b="";for(var i=1;i<50;i++){b=b+"+第"+i+"页="+i;}var b="翻页"+b;a+"\n"+b;
##分类规则
var 列表=e2Arr(getVar("源码"),".get(div.module-items a.module-item)");if(!列表[0]){var 列表=["网页可能有搜索验证，去网页看看吧"];var 标题规则=".t()";var 地址规则="@js=getVar(\"当前请求地址\");";var 图片规则=".get(img).a(data-original)";var 简介规则="@js='长按网页打开，验证后返回重新搜索即可';";var 图片底部规则="@js='';";var 左上规则="@js='';";var 右上规则="@js='';";var NEXTPAGE="";var PREPAGE="";}else{var 标题规则=".get(a).a(title)";var 地址规则=".get(a).a(href)";var 图片规则=".get(img).a(data-original)";var 简介规则=".t()";var 图片底部规则="@js='';";var 左上规则="@js='';";var 右上规则="@js='';";var NEXTPAGE="";var PREPAGE="";}
##选集规则
var 分类=e2Arr(getVar("源码"),".get(div.module-play-list)");var 线路=e2Arr(getVar("源码"),".get(div.module-tab-items div.module-tab-item)");var 简介=e2Rex(getVar("源码"),".get(div.module-info-content).t()");var 列表规则=".get(a)";var 标题规则=".t()";var 选集规则=".get(a).t()";var 选集地址规则=".get(a).a(href)";
##搜索规则
var 源码=getVar("源码");var 列表=e2Arr(源码,".get(div.module-items div.module-item)");if(!列表[0]){var 列表=["网页可能有搜索验证，去网页看看吧"];var 标题规则=".t()";var 地址规则="@js=getVar(\"当前请求地址\");";var 图片规则=".get(img).a(data-original)";var 简介规则="@js='长按网页打开，验证后返回重新搜索即可';";var 图片底部规则="@js='';";var 左上规则="@js='';";var 右上规则="@js='';";var NEXTPAGE="";var PREPAGE="";}else{var 标题规则=".get(div.module-card-item-title a).t()";var 地址规则=".get(div.module-card-item-title a).a(href)";var 图片规则=".get(img).a(data-original)";var 简介规则=".t()";var 图片底部规则="@js='';";var 左上规则="@js='';";var 右上规则="@js='';";var NEXTPAGE="";var PREPAGE="";}
##搜索翻页
var b="";for(var i=1;i<50;i=i+1){b=b+"+第"+i+"页="+i;}
"翻页"+b;
##免嗅探规则
"web="+getVar("地址");
####

#####


#####cms

####
###type
cms
###分类
cms
###标题
豪华资源
###图片
https://www.seekhill.com/wp-content/uploads/2022/03/20220318123440.png
###BaseURL
"https://hhzyapi.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
cms
###标题
速博资源
###图片
https://www.seekhill.com/wp-content/uploads/2022/03/20220318123440.png
###BaseURL
"https://subocaiji.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
cms
###标题
虎牙资源
###图片
https://www.seekhill.com/wp-content/uploads/2022/03/20220318123440.png
###BaseURL
"https://www.huyaapi.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
cms
###标题
暴风资源
###图片
https://www.seekhill.com/wp-content/uploads/2022/03/20220318123440.png
###BaseURL
"https://bfzyapi.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
cms
###标题
极速资源
###图片
https://www.seekhill.com/wp-content/uploads/2022/03/20220318123440.png
###BaseURL
"https://jszyapi.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
cms
###标题
火狐资源
###图片
https://www.seekhill.com/wp-content/uploads/2022/03/20220318123440.png
###BaseURL
"https://hhzyapi.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
cms
###标题
步步高资源
###图片
https://www.seekhill.com/wp-content/uploads/2022/03/20220318123440.png
###BaseURL
"https://api.yparse.com/api/json";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
cms
###标题
金鹰资源
###图片
https://www.seekhill.com/wp-content/uploads/2022/03/20220318123440.png
###BaseURL
"https://jyzyapi.com/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
cms
###标题
非凡资源
###图片
https://www.seekhill.com/wp-content/uploads/2022/03/20220318123440.png
###BaseURL
"http://cj.ffzyapi.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
cms
###标题
快车资源
###图片
https://www.seekhill.com/wp-content/uploads/2022/03/20220318123440.png
###BaseURL
"https://caiji.kczyapi.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
cms
###标题
量子资源
###图片
https://www.seekhill.com/wp-content/uploads/2022/03/20220318123440.png
###BaseURL
"http://cj.lziapi.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
cms
###标题
红牛资源
###图片
https://www.seekhill.com/wp-content/uploads/2022/03/20220318123440.png
###BaseURL
"https://www.hongniuzy2.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
cms
###标题
樱花资源
###图片
https://www.seekhill.com/wp-content/uploads/2022/03/20220318123440.png
###BaseURL
"https://m3u8.apiyhzy.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
cms
###标题
闪电资源
###图片
https://www.seekhill.com/wp-content/uploads/2022/03/20220318123440.png
###BaseURL
"http://sdzyapi.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
cms
###标题
光速资源
###图片
https://www.seekhill.com/wp-content/uploads/2022/03/20220318123440.png
###BaseURL
"https://api.guangsuapi.com/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
三方聚合
###标题
四个圈影视
###图片
https://www.seekhill.com/wp-content/uploads/2022/03/20220318123440.png
###BaseURL
"https://pg.fenwe078.cf/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
三方聚合
###标题
影图
###图片
https://www.seekhill.com/wp-content/uploads/2022/03/20220318123440.png
###BaseURL
"https://cj.vodimg.top/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####
####
###type
cms
###分类
三方聚合
###标题
飘零影院
###图片
https://www.seekhill.com/wp-content/uploads/2022/03/20220318123440.png
###BaseURL
"https://p2100.net/api.php/provide/vod/";
###首页地址
getVar("baseURL")+"?ac=list&pg=1";
###分类地址
getVar("baseURL")+"?ac=videolist分类&pg=翻页";
###搜索地址
getVar("baseURL")+"?wd=关键字&ac=显示&pg=翻页";
###rule
####

#####